rootProject.name = 'devexpress-demos-java'

include ':PdfDocumentApi:DocumentElements:PdfAnnotations'
include ':PdfDocumentApi:DocumentElements:PdfAttachments'
include ':PdfDocumentApi:DocumentElements:PdfBookmarks'
include ':PdfDocumentApi:DocumentProtection:PdfApplyWatermark'
include ':PdfDocumentApi:DocumentProtection:PdfEncryptPassword'
include ':PdfDocumentApi:DocumentProtection:PdfRedaction'
include ':PdfDocumentApi:Forms:PdfCreateForm'
include ':PdfDocumentApi:Forms:PdfRemoveFlattenForm'
include ':PdfDocumentApi:GenerateDocument:PdfGenerateInvoice'
include ':PdfDocumentApi:ManagePages:PdfClearPages'
include ':PdfDocumentApi:ManagePages:PdfManagePages'
include ':PdfDocumentApi:MergeSplit:PdfMergeDocuments'
include ':PdfDocumentApi:MergeSplit:PdfSplitDocuments'
include ':PdfDocumentApi:SearchExtract:PdfExtractImages'
include ':PdfDocumentApi:SearchExtract:PdfFindHighlight'
include ':PdfDocumentApi:SearchExtract:PdfXMPMetadata'
include ':PowerPointPresentationApi:DocumentConversion:PresentationToImage'
include ':PowerPointPresentationApi:DocumentConversion:PresentationToPdf'
include ':PowerPointPresentationApi:DocumentConversion:PresentationToPresentation'
include ':PowerPointPresentationApi:DocumentElements:PresentationNotes'
include ':PowerPointPresentationApi:DocumentElements:PresentationShapes'
include ':PowerPointPresentationApi:DocumentElements:PresentationTables'
include ':PowerPointPresentationApi:DocumentProtection:PresentationEncryptPassword'
include ':PowerPointPresentationApi:DocumentProtection:PresentationInspectAndSanitize'
include ':PowerPointPresentationApi:DocumentProtection:PresentationSecureDocumentLoading'
include ':PowerPointPresentationApi:MergeSplit:PresentationMerge'
include ':PowerPointPresentationApi:MergeSplit:PresentationSplit'
include ':PowerPointPresentationApi:SearchExtract:PresentationExtractImages'
include ':PowerPointPresentationApi:SearchExtract:PresentationExtractText'
include ':PowerPointPresentationApi:SearchExtract:PresentationFindReplace'
include ':PowerPointPresentationApi:SearchExtract:PresentationMetadata'
include ':BarcodeGenerationApi:BarcodeAztec'
include ':BarcodeGenerationApi:BarcodeQrCode'
include ':BarcodeGenerationApi:BarcodeMicroQrCode'
include ':BarcodeGenerationApi:BarcodeQrCodeGs1'
include ':BarcodeGenerationApi:BarcodeDataMatrix'
include ':BarcodeGenerationApi:BarcodeDataMatrixGs1'
include ':BarcodeGenerationApi:BarcodePdf417'
include ':BarcodeGenerationApi:BarcodeIntelligentMail'
include ':BarcodeGenerationApi:BarcodeCodabar'
include ':BarcodeGenerationApi:BarcodeCode11'
include ':BarcodeGenerationApi:BarcodeCode128'
include ':BarcodeGenerationApi:BarcodeGs1128'
include ':BarcodeGenerationApi:BarcodeCode39'
include ':BarcodeGenerationApi:BarcodeCode39Extended'
include ':BarcodeGenerationApi:BarcodeCode93'
include ':BarcodeGenerationApi:BarcodeCode93Extended'
include ':BarcodeGenerationApi:BarcodeDeutschePostLeitcode'
include ':BarcodeGenerationApi:BarcodeDeutschePostIdentcode'
include ':BarcodeGenerationApi:BarcodeEan8'
include ':BarcodeGenerationApi:BarcodeEan13'
include ':BarcodeGenerationApi:BarcodeGs1DataBar'
include ':BarcodeGenerationApi:BarcodeIndustrial2of5'
include ':BarcodeGenerationApi:BarcodeInterleaved2of5'
include ':BarcodeGenerationApi:BarcodeMatrix2of5'
include ':BarcodeGenerationApi:BarcodeMsiPlessey'
include ':BarcodeGenerationApi:BarcodePharmacode'
include ':BarcodeGenerationApi:BarcodePostNet'
include ':BarcodeGenerationApi:BarcodeIntelligentMailPackage'
include ':BarcodeGenerationApi:BarcodeSscc18'
include ':BarcodeGenerationApi:BarcodeItf14'
include ':BarcodeGenerationApi:BarcodeUpcSupplemental2'
include ':BarcodeGenerationApi:BarcodeUpcSupplemental5'
include ':BarcodeGenerationApi:BarcodeUpca'
include ':BarcodeGenerationApi:BarcodeUpce0'
include ':BarcodeGenerationApi:BarcodeUpce1'
